package main

import "fmt"

var arr []int

// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal
// numbers are:
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
//
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
//
// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

func main() {
	//2500 is learned after experiment. The array includes the result
	arr = make([]int, 5000)
	for i := range arr {
		arr[i] = (i * (3*i - 1)) / 2
	}
	min := int(^uint(0) >> 1)
	for i := 1; i < len(arr); i++ {
		for j := i + 1; j < len(arr); j++ {
			if isPentagonal(arr[j]-arr[i]) && isPentagonal(arr[j]+arr[i]) && arr[j]-arr[i] < min {
				min = arr[j] - arr[i]
			}
		}
	}
	fmt.Println("044/ what is the value of D?")
	fmt.Println(min)
}

func isPentagonal(in int) bool {
	return search(in, 0, len(arr)-1)
}

func search(value, low, high int) bool {
	if high < low {
		return false
	}
	mid := low + (high-low)/2
	if arr[mid] > value {
		return search(value, low, mid-1)
	} else if arr[mid] < value {
		return search(value, mid+1, high)
	}
	return true
}
